#Stage 1
#Base Image
FROM node:18-alpine AS builder

# Here is Work directory
WORKDIR /app

# Copy and install dependencies from package.json and package-lock.json
COPY package.json package-lock.json ./

# Installation here
RUN npm install

#Copy the stuff and run the build
COPY . .
RUN npm run build

#Stage 2
# Distroless Image
FROM gcr.io/distroless/nodejs:18

#work directory
WORKDIR /app

# Copy required files from builder (Stage 1)
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Expose port
EXPOSE 5173

# Run
# Need to define this path (node_modules/.bin/serve) as the app is not reading it automatically in distroless.
CMD [ "node_modules/.bin/serve", "-s", "dist", "-l", "5173" ]

